language: node_js
node_js:
  - "7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - gcc-4.9
      - libc6-dev
before_install:
  - export CC=/usr/bin/gcc-4.9;
  - export CXX=/usr/bin/g++-4.9;  
before_script:
  - npm install
  - npm i -g lumo-cljs
  - lumo -c src build.cljs
  - npm i -g exp
  - exp login -u $EXPO_USERNAME -p $EXPO_PASSWORD
script: exp publish
